import { shallowRef } from 'vue'
import type { RouteRecordRaw } from '../../types'
import { isRouteName } from '../../types/typeGuards'
import type { RouteRecordNameGeneric } from '../../typed-routes'
import { normalizeRecordProps } from '../../matcher'
import { isAbsolutePath } from '../../utils'
import { diagnostics } from '../../diagnostics'
import type {
  EXPERIMENTAL_Resolver_Base,
  RecordName,
} from './resolver-abstract'
import { createResolve } from './resolver-fixed'
import {
  MatcherPatternPathDynamic,
  MatcherPatternPathStatic,
  type MatcherPatternPath,
  type MatcherPatternPathDynamic_ParamOptions,
} from './matchers/matcher-pattern'
import { parseClassicPath } from './matchers/parse-classic-path'
import {
  comparePathScore,
  getPathScore,
  type PathScore,
} from './matchers/path-score'
import {
  normalizeRouteRecord,
  type EXPERIMENTAL_RouteRecord_Matchable,
  type EXPERIMENTAL_RouteRecordNormalized,
  type EXPERIMENTAL_RouteRecordNormalized_Matchable,
  type EXPERIMENTAL_RouteRecordRaw,
} from '../router'

/**
 * Record accepted by {@link createDynamicResolver} and
 * {@link EXPERIMENTAL_ResolverDynamic.addRoute}: a classic route record (with a
 * string `path`, `children`, `alias`, etc.) or an experimental record (with
 * matcher patterns and a `parent`), like the ones generated at build time.
 */
export type EXPERIMENTAL_ResolverDynamicRecordRaw =
  | RouteRecordRaw
  | EXPERIMENTAL_RouteRecordRaw
  | EXPERIMENTAL_RouteRecordNormalized

/**
 * Resolver that allows adding and removing routes at runtime. Created with
 * {@link createDynamicResolver}.
 */
export interface EXPERIMENTAL_ResolverDynamic<
  TRecord,
> extends EXPERIMENTAL_Resolver_Base<TRecord> {
  /**
   * Add a new route record as the child of an existing route.
   *
   * @param parentName - name of the parent route
   * @param route - route record to add
   * @returns a function that removes the added route
   */
  addRoute(
    parentName: NonNullable<RouteRecordNameGeneric>,
    route: EXPERIMENTAL_ResolverDynamicRecordRaw
  ): () => void

  /**
   * Add a new route record.
   *
   * @param route - route record to add
   * @returns a function that removes the added route
   */
  addRoute(route: EXPERIMENTAL_ResolverDynamicRecordRaw): () => void

  /**
   * Remove an existing route by its name or its record. This also removes its
   * children and aliases.
   *
   * @param nameOrRecord - name or record of the route to remove
   */
  removeRoute(nameOrRecord: NonNullable<RouteRecordNameGeneric> | TRecord): void

  /**
   * Remove all the routes.
   */
  clearRoutes(): void
}

/**
 * Records that are removed with a record.
 */
interface RecordNode {
  children: EXPERIMENTAL_RouteRecordNormalized[]
  aliases: EXPERIMENTAL_RouteRecordNormalized[]
}

/**
 * A call to `addRoute()`, kept to add the route again after HMR.
 */
interface AddedRoute {
  parentName: RecordName | undefined
  raw: EXPERIMENTAL_ResolverDynamicRecordRaw
  record: EXPERIMENTAL_RouteRecordNormalized | undefined
}

/**
 * Initial records of each dynamic resolver, used by HMR.
 */
const initialRecordsMap: WeakMap<
  object,
  readonly EXPERIMENTAL_ResolverDynamicRecordRaw[]
> | null = __DEV__ ? new WeakMap() : null

/**
 * Creates a resolver that allows adding and removing routes at runtime. It
 * accepts the route records generated by `vue-router/auto-resolver?dynamic`
 * and the route records of the classic router (`path: '/users/:id'`,
 * `children`, `alias`, `component`, etc.). Records are ranked with the same
 * score as the generated ones. Paths are strict: `/about` doesn't match
 * `/about/`.
 *
 * @param records - initial records
 * @returns a resolver that can be passed to `experimental_createRouter()`
 *
 * @example
 * ```ts
 * const router = experimental_createRouter({
 *   history: createWebHistory(),
 *   resolver: createDynamicResolver([
 *     { path: '/', component: Home },
 *     { path: '/users/:id', name: 'user', component: User },
 *   ]),
 * })
 * router.addRoute({ path: '/about', name: 'about', component: About })
 * ```
 */
export function createDynamicResolver(
  records: readonly EXPERIMENTAL_ResolverDynamicRecordRaw[] = []
): EXPERIMENTAL_ResolverDynamic<EXPERIMENTAL_RouteRecordNormalized_Matchable> {
  type TRecord = EXPERIMENTAL_RouteRecordNormalized_Matchable
  // ordered matchable records, aliases included
  const matchers: TRecord[] = []
  // original records by name
  const recordMap = new Map<RecordName, TRecord>()
  const nodes = new Map<EXPERIMENTAL_RouteRecordNormalized, RecordNode>()
  const scores = new Map<EXPERIMENTAL_RouteRecordNormalized, PathScore>()
  // full classic path of the records created from a classic record
  const classicPaths = new Map<EXPERIMENTAL_RouteRecordNormalized, string>()
  const addedRoutes: AddedRoute[] = []
  // invalidates computed values that call `resolve()` when routes change
  const version = shallowRef(0)
  const resolveFn = createResolve(matchers, recordMap)

  function getNode(record: EXPERIMENTAL_RouteRecordNormalized): RecordNode {
    let node = nodes.get(record)
    if (!node) nodes.set(record, (node = { children: [], aliases: [] }))
    return node
  }

  function addRoute(
    parentOrRoute:
      | NonNullable<RouteRecordNameGeneric>
      | EXPERIMENTAL_ResolverDynamicRecordRaw,
    route?: EXPERIMENTAL_ResolverDynamicRecordRaw
  ): () => void {
    let parentName: RecordName | undefined
    if (isRouteName(parentOrRoute)) {
      parentName = parentOrRoute
      if (__DEV__ && !recordMap.has(parentName)) {
        diagnostics.VUE_ROUTER_R0001({ name: String(parentName) })
      }
    } else {
      route = parentOrRoute
    }

    const added: AddedRoute = {
      parentName,
      raw: route!,
      record: addRecord(route!, parentName),
    }
    addedRoutes.push(added)
    version.value++
    return () => {
      if (added.record) removeRoute(added.record)
    }
  }

  function addRecord(
    raw: EXPERIMENTAL_ResolverDynamicRecordRaw,
    parentName?: RecordName
  ): EXPERIMENTAL_RouteRecordNormalized | undefined {
    const parent = parentName == null ? undefined : recordMap.get(parentName)
    return typeof raw.path === 'string'
      ? insertClassicRecord(raw as RouteRecordRaw, parent)
      : insertRecord(
          raw as
            | EXPERIMENTAL_RouteRecordRaw
            | EXPERIMENTAL_RouteRecordNormalized,
          parent
        )
  }

  /**
   * Inserts an experimental record.
   *
   * @param raw - record to add, normalized if needed
   * @param parent - parent passed to `addRoute()`
   */
  function insertRecord(
    raw: EXPERIMENTAL_RouteRecordRaw | EXPERIMENTAL_RouteRecordNormalized,
    parent?: EXPERIMENTAL_RouteRecordNormalized
  ): EXPERIMENTAL_RouteRecordNormalized {
    const record = (
      'leaveGuards' in raw ? raw : normalizeRouteRecord(raw as TRecord)
    ) as EXPERIMENTAL_RouteRecordNormalized
    if (parent) record.parent = parent

    if (record.aliasOf) {
      getNode(record.aliasOf).aliases.push(record)
    } else if (record.name != null) {
      // replace any existing route with the same name
      const existing = recordMap.get(record.name)
      if (existing) removeRecord(existing)
    }
    attach(record)
    return record
  }

  /**
   * Normalizes and inserts a classic record, its aliases, and its children.
   *
   * @param raw - record to add
   * @param parent - parent record
   * @param originalRecord - when adding the children of an alias, the original child
   * @returns the original record
   */
  function insertClassicRecord(
    raw: RouteRecordRaw,
    parent?: EXPERIMENTAL_RouteRecordNormalized,
    originalRecord?: EXPERIMENTAL_RouteRecordNormalized
  ): EXPERIMENTAL_RouteRecordNormalized | undefined {
    if (
      __DEV__ &&
      (raw.strict === false || raw.sensitive || raw.end === false)
    ) {
      diagnostics.VUE_ROUTER_R0131({ path: raw.path })
    }

    const isRootAdd = !originalRecord
    const components =
      'components' in raw
        ? raw.components
        : raw.component && { default: raw.component }
    const isMatchable = !!(
      raw.name ||
      (components && Object.keys(components).length) ||
      raw.redirect
    )
    const paths = [raw.path].concat(raw.alias || [])
    const props = normalizeRecordProps(raw)
    let mainRecord: EXPERIMENTAL_RouteRecordNormalized | undefined

    for (let i = 0; i < paths.length; i++) {
      let path = paths[i]
      // Build up the path for nested routes if the child isn't an absolute
      // route. Only add the / delimiter if the child path isn't empty and if the
      // parent path doesn't have a trailing slash
      if (parent && !isAbsolutePath(path)) {
        const parentPath = getClassicPath(parent)
        path =
          parentPath + (path && (parentPath.endsWith('/') ? '' : '/') + path)
      }

      if (__DEV__ && path === '*') {
        throw new Error(
          'Catch all routes ("*") must now be defined using a param with a custom regexp.\n' +
            'See more at https://router.vuejs.org/guide/migration/#Removed-star-or-catch-all-routes.'
        )
      }

      const aliasOf = originalRecord || (i ? mainRecord : undefined)
      const record = normalizeRouteRecord({
        name: aliasOf
          ? aliasOf.name
          : isMatchable
            ? (raw.name ?? Symbol(__DEV__ ? path : ''))
            : undefined,
        path: parseClassicPathWithParent(path, parent),
        // aliases share the components with the original record
        components: aliasOf ? aliasOf.components : components || undefined,
        meta: raw.meta || {},
        props,
        redirect: raw.redirect,
        beforeEnter: raw.beforeEnter,
        parent,
        aliasOf,
      } as EXPERIMENTAL_RouteRecord_Matchable) as EXPERIMENTAL_RouteRecordNormalized
      classicPaths.set(record, path)

      if (__DEV__ && parent && isAbsolutePath(raw.path)) {
        checkMissingParamsInAbsolutePath(record, parent)
      }

      if (aliasOf) {
        getNode(aliasOf).aliases.push(record)
        if (__DEV__) checkSameParams(aliasOf, record)
      } else {
        mainRecord = record
        // replace any existing route with the same name
        if (isRootAdd && raw.name != null) {
          if (__DEV__) checkSameNameAsAncestor(raw, parent)
          const existing = recordMap.get(raw.name)
          if (existing) removeRecord(existing)
        }
      }

      attach(record)

      if (raw.children) {
        const originalChildren =
          originalRecord && getNode(originalRecord).children
        for (let j = 0; j < raw.children.length; j++) {
          const child = raw.children[j]
          if (
            __DEV__ &&
            !originalChildren &&
            raw.name != null &&
            child.name == null &&
            !child.path &&
            !child.children?.length
          ) {
            diagnostics.VUE_ROUTER_R0103({ name: String(raw.name) })
          }
          insertClassicRecord(child, record, originalChildren?.[j])
        }
      }

      // the children of the aliases are aliases of the children of the first record
      originalRecord = originalRecord || record
    }

    return mainRecord
  }

  /**
   * Links a record to its parent and adds it to the matchers if it can be
   * matched (if it has a name and a path).
   */
  function attach(record: EXPERIMENTAL_RouteRecordNormalized) {
    getNode(record)
    const { parent } = record
    // both are aliases or both are not aliases so the children of an alias
    // match the children of the original record by index
    if (parent && !record.aliasOf === !parent.aliasOf) {
      getNode(parent).children.push(record)
    }

    if (record.name != null && record.path) {
      insertMatcher(record as TRecord)
    }
  }

  /**
   * Returns the full classic path of a record. Records created from patterns
   * are converted back to the classic syntax.
   */
  function getClassicPath(record: EXPERIMENTAL_RouteRecordNormalized): string {
    return (
      classicPaths.get(record) ??
      (record.path ? patternToClassicPath(record.path) : '/')
    )
  }

  function insertMatcher(record: TRecord) {
    matchers.splice(findInsertionIndex(record), 0, record)
    if (!record.aliasOf) {
      recordMap.set(record.name, record)
    }
  }

  function getScore(record: EXPERIMENTAL_RouteRecordNormalized): PathScore {
    let score = scores.get(record)
    if (!score) scores.set(record, (score = getPatternScore(record.path!)))
    return score
  }

  /**
   * Performs a binary search to find the insertion index of a record. Records
   * are sorted by their score. If scores are tied, descendants come before
   * ancestors. If there's still a tie, new routes are inserted after existing
   * routes.
   */
  function findInsertionIndex(record: TRecord): number {
    const score = getScore(record)
    let lower = 0
    let upper = matchers.length

    while (lower !== upper) {
      const mid = (lower + upper) >> 1
      if (comparePathScore(score, getScore(matchers[mid])) < 0) {
        upper = mid
      } else {
        lower = mid + 1
      }
    }

    // check for an ancestor with the same score
    let ancestor: EXPERIMENTAL_RouteRecordNormalized | null | undefined = record
    while ((ancestor = ancestor.parent)) {
      if (
        ancestor.name != null &&
        ancestor.path &&
        !comparePathScore(score, getScore(ancestor))
      ) {
        const index = matchers.lastIndexOf(ancestor as TRecord, upper - 1)
        if (index > -1) upper = index
        break
      }
    }

    return upper
  }

  function removeRoute(
    nameOrRecord:
      | NonNullable<RouteRecordNameGeneric>
      | EXPERIMENTAL_RouteRecordNormalized
  ) {
    const record = isRouteName(nameOrRecord)
      ? recordMap.get(nameOrRecord)
      : nameOrRecord
    if (record && nodes.has(record)) {
      removeRecord(record)
      // removed routes are not added again by HMR
      for (let i = addedRoutes.length - 1; i >= 0; i--) {
        const added = addedRoutes[i].record
        if (!added || !nodes.has(added)) addedRoutes.splice(i, 1)
      }
      version.value++
    } else if (__DEV__ && isRouteName(nameOrRecord)) {
      diagnostics.VUE_ROUTER_R0002({ name: String(nameOrRecord) })
    }
  }

  /**
   * Removes a record, its children, and its aliases.
   */
  function removeRecord(record: EXPERIMENTAL_RouteRecordNormalized) {
    const node = nodes.get(record)
    if (!node) return
    nodes.delete(record)
    scores.delete(record)
    classicPaths.delete(record)
    if (record.name != null && recordMap.get(record.name) === record) {
      recordMap.delete(record.name)
    }
    const index = matchers.indexOf(record as TRecord)
    if (index > -1) matchers.splice(index, 1)
    node.children.forEach(removeRecord)
    node.aliases.forEach(removeRecord)
  }

  function clear() {
    matchers.length = 0
    recordMap.clear()
    nodes.clear()
    scores.clear()
    classicPaths.clear()
  }

  function clearRoutes() {
    clear()
    addedRoutes.length = 0
    version.value++
  }

  for (const record of records) addRecord(record)

  const resolver: EXPERIMENTAL_ResolverDynamic<TRecord> = {
    resolve: ((...args: Parameters<typeof resolveFn>) => {
      // track the routes so `computed()`s using `resolve()` are invalidated
      version.value
      const [to, currentLocation] = args
      if (__DEV__ && typeof to === 'object' && to.name != null) {
        const record = recordMap.get(to.name)
        if (record) {
          const patternParams = getPatternParams(record.path)
          const keys = patternParams.map(([name]) => name)
          const invalidParams = Object.keys(to.params || {}).filter(
            name => !keys.includes(name)
          )
          if (invalidParams.length) {
            diagnostics.VUE_ROUTER_R0100({
              params: invalidParams.join('", "'),
              inherited: '',
            })
          }

          const params = { ...currentLocation?.params, ...to.params }
          for (const [name, repeatable, optional] of patternParams) {
            const value = params[name]
            if (
              !optional &&
              (value == null ||
                value === '' ||
                (repeatable && Array.isArray(value) && !value.length))
            ) {
              diagnostics.VUE_ROUTER_R0132({
                param: name,
                name: String(to.name),
              })
            }
          }
        }
      }
      return resolveFn(...args)
    }) as typeof resolveFn,
    getRoutes: () => matchers,
    getRoute: name => recordMap.get(name),
    addRoute,
    removeRoute,
    clearRoutes,
  }

  if (__DEV__) {
    initialRecordsMap!.set(resolver, records)
    // not enumerable so the router doesn't expose it
    Object.defineProperty(resolver, '_hmrUpdate', {
      /**
       * Replaces the initial records with the ones of a new resolver created
       * by HMR and adds again the routes added with `addRoute()`.
       */
      value(newResolver: object) {
        clear()
        for (const record of initialRecordsMap!.get(newResolver) || []) {
          addRecord(record)
        }
        for (const added of addedRoutes) {
          const { raw, parentName } = added
          // experimental records reference the old parent
          if (typeof raw.path !== 'string' && raw.parent?.name != null) {
            raw.parent = recordMap.get(raw.parent.name)
          }
          added.record = addRecord(raw, parentName)
        }
        version.value++
      },
    })
  }

  return resolver
}

/**
 * Parses a classic path and reuses the param parsers of the parent for the
 * params it inherits.
 */
function parseClassicPathWithParent(
  path: string,
  parent: EXPERIMENTAL_RouteRecordNormalized | undefined
): MatcherPatternPath {
  const pattern = parseClassicPath(path)
  if (
    pattern instanceof MatcherPatternPathDynamic &&
    parent?.path instanceof MatcherPatternPathDynamic
  ) {
    const parentParams = parent.path.params as Record<
      string,
      MatcherPatternPathDynamic_ParamOptions
    >
    for (const name in pattern.params) {
      const parser = parentParams[name]?.[0]
      if (parser) {
        const [, repeatable, optional] = pattern.params[name]
        pattern.params[name] = [parser, repeatable, optional]
      }
    }
  }
  return pattern
}

type PatternParam = [name: string, repeatable?: boolean, optional?: boolean]

/**
 * Returns the params of a pattern as `[name, repeatable, optional]`.
 */
function getPatternParams(
  pattern: MatcherPatternPath | undefined
): PatternParam[] {
  return pattern instanceof MatcherPatternPathDynamic
    ? Object.entries(
        pattern.params as Record<string, MatcherPatternPathDynamic_ParamOptions>
      ).map(([name, [, repeatable, optional]]) => [name, repeatable, optional])
    : []
}

/**
 * Computes the score of a path pattern. Custom patterns are ranked last.
 */
function getPatternScore(pattern: MatcherPatternPath): PathScore {
  return pattern instanceof MatcherPatternPathDynamic
    ? getPathScore(
        pattern.pathParts,
        Object.values(
          pattern.params as Record<
            string,
            MatcherPatternPathDynamic_ParamOptions
          >
        )
      )
    : pattern instanceof MatcherPatternPathStatic
      ? getPathScore(pattern.path.split('/').filter(Boolean), [])
      : []
}

/**
 * Converts a pattern back to the classic syntax so classic children can be
 * added to records created from patterns.
 */
function patternToClassicPath(pattern: MatcherPatternPath): string {
  if (pattern instanceof MatcherPatternPathStatic) return pattern.path
  if (!(pattern instanceof MatcherPatternPathDynamic)) {
    throw new Error('Cannot add a relative child route to a custom path')
  }
  const params = getPatternParams(pattern)
  let paramIndex = 0
  const partToPath = (part: string | number) => {
    if (typeof part === 'string') return part
    const [name, repeatable, optional] = params[paramIndex++]
    return (
      ':' +
      name +
      (part === 0 ? '(.*)' : '') +
      (repeatable ? (optional ? '*' : '+') : optional ? '?' : '')
    )
  }
  return (
    '/' +
    pattern.pathParts
      .map(part =>
        typeof part === 'object'
          ? part.map(partToPath).join('')
          : partToPath(part)
      )
      .join('/') +
    (pattern.trailingSlash ? '/' : '')
  )
}

/**
 * Returns the full path of a record for warnings.
 */
function getRecordPath(record: EXPERIMENTAL_RouteRecordNormalized): string {
  return record.path ? patternToClassicPath(record.path) : ''
}

function isSameParam(a: PatternParam, b: PatternParam): boolean {
  return a[0] === b[0] && !a[1] === !b[1] && !a[2] === !b[2]
}

function checkMissingParamsInAbsolutePath(
  record: EXPERIMENTAL_RouteRecordNormalized,
  parent: EXPERIMENTAL_RouteRecordNormalized
) {
  const keys = getPatternParams(record.path)
  for (const key of getPatternParams(parent.path)) {
    if (!keys.find(k => isSameParam(k, key))) {
      diagnostics.VUE_ROUTER_R0104({
        path: getRecordPath(record),
        name: key[0],
        parent: getRecordPath(parent),
      })
      return
    }
  }
}

/**
 * Check if a path and its alias have the same required params.
 *
 * @param a - original record
 * @param b - alias record
 */
function checkSameParams(
  a: EXPERIMENTAL_RouteRecordNormalized,
  b: EXPERIMENTAL_RouteRecordNormalized
) {
  for (const [x, y] of [
    [a, b],
    [b, a],
  ]) {
    const yKeys = getPatternParams(y.path)
    for (const key of getPatternParams(x.path)) {
      if (!key[2] && !yKeys.find(k => isSameParam(key, k))) {
        diagnostics.VUE_ROUTER_R0102({
          alias: getRecordPath(b),
          original: getRecordPath(a),
          name: key[0],
        })
        return
      }
    }
  }
}

function checkSameNameAsAncestor(
  raw: RouteRecordRaw,
  parent: EXPERIMENTAL_RouteRecordNormalized | undefined
) {
  for (let ancestor = parent; ancestor; ancestor = ancestor.parent!) {
    if (ancestor.name === raw.name) {
      throw new Error(
        `A route named "${String(raw.name)}" has been added as a ${
          parent === ancestor ? 'child' : 'descendant'
        } of a route with the same name. Route names must be unique and a nested route cannot use the same name as an ancestor.`
      )
    }
  }
}
