packages:
  - 'packages/*'

shamefullyHoist: true

overrides:
  '@babel/generator': '^8.0.0'
  '@babel/types': '^8.0.0'
  '@types/node': '^24.10.4'
  '@vue/compiler-core': '3.6.0-rc.6'
  '@vue/compiler-dom': '3.6.0-rc.6'
  '@vue/compiler-sfc': '3.6.0-rc.6'
  '@vue/compiler-ssr': '3.6.0-rc.6'
  '@vue/compiler-vapor': '3.6.0-rc.6'
  '@vue/reactivity': '3.6.0-rc.6'
  '@vue/runtime-core': '3.6.0-rc.6'
  '@vue/runtime-dom': '3.6.0-rc.6'
  '@vue/runtime-vapor': '3.6.0-rc.6'
  '@vue/server-renderer': '3.6.0-rc.6'
  '@vue/shared': '3.6.0-rc.6'
  'vite': '^8.2.0'
  'vue': '3.6.0-rc.6'

peerDependencyRules:
  ignoreMissing:
    - react
    - react-dom
    - '@types/react'

allowBuilds:
  chromedriver: true
  esbuild: true
  geckodriver: true
  simple-git-hooks: true
  '@nightwatch/nightwatch-inspector': false
detect_chromedriver_version: true
