packages:
  - 'packages/*'

shamefullyHoist: true

overrides:
  '@babel/generator': '^8.0.6'
  '@babel/types': '^8.0.6'
  '@types/node': '^26.6.4'
  '@vue/compiler-sfc': '^3.6.0-beta.5'
  '@vue/runtime-dom': '^3.6.0-beta.5'
  '@vue/server-renderer': '^3.6.0-beta.5'
  'vite': '^8.3.3'
  'vue': '^3.6.0-beta.5'

peerDependencyRules:
  ignoreMissing:
    - react
    - react-dom
    - '@types/react'

allowBuilds:
  chromedriver: true
  esbuild: true
  geckodriver: true
  simple-git-hooks: true
  '@nightwatch/nightwatch-inspector': false
