/**
 * Types of `vue-router/auto-resolver?dynamic`. This file must stay a global
 * script (no top level import or export) so the module declaration with a
 * query is ambient. The generated `typed-router.d.ts` references it.
 */

declare module 'vue-router/auto-resolver?dynamic' {
  import type {
    EXPERIMENTAL_ResolverDynamic,
    EXPERIMENTAL_RouteRecordNormalized_Matchable,
    EXPERIMENTAL_Router,
  } from 'vue-router/experimental'

  /**
   * Handles HMR. Routes added at runtime with `addRoute()` are kept.
   * Generated by vue-router
   */
  export function handleHotUpdate(router: EXPERIMENTAL_Router): void

  /**
   * Dynamic resolver created with the routes generated at build time. Routes
   * can be added and removed at runtime.
   * Generated by vue-router
   */
  export const resolver: EXPERIMENTAL_ResolverDynamic<EXPERIMENTAL_RouteRecordNormalized_Matchable>
}
