import type {
  EXPERIMENTAL_Router,
  EXPERIMENTAL_RouterOptions,
} from 'vue-router/experimental'

/**
 * Handles HMR.
 * Generated by unplugin-vue-router
 */
export declare function handleHotUpdate(router: EXPERIMENTAL_Router): void

/**
 * Custom resolver automatically generated at build time
 * Generated by unplugin-vue-router
 */
export declare const resolver: EXPERIMENTAL_RouterOptions['resolver']
