/**
 * TODO: remove the declaration if possible when merging unplugin-vue-router
 * into this monorepo in v6
 */

import type {
  EXPERIMENTAL_Router,
  EXPERIMENTAL_RouterOptions,
} from 'vue-router/experimental'

/**
 * Setups hot module replacement for the resolver.
 * Generated by unplugin-vue-router
 *
 * @param router - The router instance
 * @param hotUpdateCallback - Callback to be called after replacing the resolver and before the navigation
 *
 * @example
 *
 * ```ts
 * import { createWebHistory } from 'vue-router'
 * import { experimental_createRouter as createRouter } from 'vue-router/experimental'
 * import { resolver, handleHotUpdate } from 'vue-router/auto-resolver'
 * const router = createRouter({
 *   history: createWebHistory(),
 *   resolver,
 * })
 * if (import.meta.hot) {
 *   handleHotUpdate(router)
 * }
 * ```
 */
export declare function handleHotUpdate(
  router: EXPERIMENTAL_Router,
  hotUpdateCallback?: (
    newResolver: EXPERIMENTAL_RouterOptions['resolver']
  ) => void
): void

/**
 * Custom resolver automatically generated at build time
 * Generated by unplugin-vue-router
 */
export declare const resolver: EXPERIMENTAL_RouterOptions['resolver']

// TODO:move to the generated route map so it can import the correct version (custom resolvers or not)
// Make the macros globally available
// declare global {
//   const definePage: (typeof import("vue-router/experimental"))["definePage"];
// }
