import { test, expect, type Page } from '@playwright/test'
import { reloadKeepingState } from './utils'

// resolved against `baseURL` from playwright.config.ts
const BASE = '/modal'

// scope to a user's <li> so we can pick its "Details" button by role
const userItem = (page: Page, name: string) =>
  page.getByRole('listitem').filter({ hasText: name })

test.describe('modal', () => {
  test('changes the url', async ({ page }) => {
    await page.goto(BASE + '/')
    await expect(page.getByRole('heading', { name: 'Home' })).toBeVisible()
    await expect(page.locator('dialog')).toBeHidden()
    await expect(page.locator('.child')).toContainText('child')

    await userItem(page, 'Jessica')
      .getByRole('button', { name: 'Details' })
      .click()
    await expect(page).toHaveURL(BASE + '/users/1')
    await expect(page.locator('dialog')).toBeVisible()
    await expect(page.locator('dialog')).toContainText('User #1')
    await expect(page.locator('.child')).toContainText('child')
  })

  test('can close and reopen the modal through history', async ({ page }) => {
    await page.goto(BASE + '/')
    await expect(page.getByRole('heading', { name: 'Home' })).toBeVisible()

    await userItem(page, 'Jessica')
      .getByRole('button', { name: 'Details' })
      .click()
    await expect(page.locator('dialog')).toBeVisible()
    await page.goBack()
    await expect(page.locator('dialog')).toBeHidden()
    await expect(page).toHaveURL(BASE + '/')
    await page.goForward()
    await expect(page.locator('dialog')).toBeVisible()
    await expect(page).toHaveURL(BASE + '/users/1')
    await page.goBack()
    await expect(page.locator('dialog')).toBeHidden()
    await expect(page).toHaveURL(BASE + '/')
    await page.goForward()
    await expect(page.locator('dialog')).toBeVisible()
    await expect(page).toHaveURL(BASE + '/users/1')
  })

  test('can keep the modal when reloading', async ({ page }) => {
    await page.goto(BASE + '/')
    await expect(page.getByRole('heading', { name: 'Home' })).toBeVisible()

    await userItem(page, 'Jessica')
      .getByRole('button', { name: 'Details' })
      .click()
    await expect(page.locator('dialog')).toBeVisible()
    // the modal app restores its background view from history.state on reload
    await reloadKeepingState(page)
    await expect(page).toHaveURL(BASE + '/users/1')
    await expect(page.getByRole('heading', { name: 'Home' })).toBeVisible()
    await expect(page.locator('dialog')).toBeVisible()
    await page.goBack()
    await expect(page).toHaveURL(BASE + '/')
    await expect(page.getByRole('heading', { name: 'Home' })).toBeVisible()
    await expect(page.locator('dialog')).toBeHidden()
  })

  test('can pass through the modal and then back', async ({ page }) => {
    await page.goto(BASE + '/')
    await expect(page.getByRole('heading', { name: 'Home' })).toBeVisible()
    await expect(page.locator('dialog')).toBeHidden()

    await page.getByRole('link', { name: 'Jessica' }).click()
    await expect(page).toHaveURL(BASE + '/users/1')
    await expect(page.getByRole('heading', { name: 'User #1' })).toBeVisible()
    await page.getByRole('link', { name: 'Back home' }).click()
    await expect(page).toHaveURL(BASE + '/')
    await expect(page.getByRole('heading', { name: 'Home' })).toBeVisible()
    await page.getByRole('link', { name: 'James' }).click()
    await expect(page).toHaveURL(BASE + '/users/2')
    await expect(page.getByRole('heading', { name: 'User #2' })).toBeVisible()
    await page.getByRole('link', { name: 'Back home' }).click()
    await expect(page).toHaveURL(BASE + '/')
    await expect(page.getByRole('heading', { name: 'Home' })).toBeVisible()
    await userItem(page, 'Jessica')
      .getByRole('button', { name: 'Details' })
      .click()
    await expect(page).toHaveURL(BASE + '/users/1')
    await expect(page.locator('dialog')).toBeVisible()
    await page.goBack()
    await expect(page.locator('dialog')).toBeHidden()
    await expect(page).toHaveURL(BASE + '/')
    await page.goBack()
    await expect(page).toHaveURL(BASE + '/users/2')
    await expect(page.getByRole('heading', { name: 'User #2' })).toBeVisible()
    await page.goBack()
    await expect(page).toHaveURL(BASE + '/')
    await expect(page.getByRole('heading', { name: 'Home' })).toBeVisible()
    await page.goBack()
    await expect(page).toHaveURL(BASE + '/users/1')
    await expect(page.getByRole('heading', { name: 'User #1' })).toBeVisible()
    await page.goBack()
    await expect(page).toHaveURL(BASE + '/')
    await expect(page.getByRole('heading', { name: 'Home' })).toBeVisible()
    await page.goForward()
    await expect(page).toHaveURL(BASE + '/users/1')
    await expect(page.getByRole('heading', { name: 'User #1' })).toBeVisible()
    await page.goForward()
    await expect(page).toHaveURL(BASE + '/')
    await expect(page.getByRole('heading', { name: 'Home' })).toBeVisible()
    await page.goForward()
    await expect(page).toHaveURL(BASE + '/users/2')
    await expect(page.getByRole('heading', { name: 'User #2' })).toBeVisible()
    await page.goForward()
    await expect(page).toHaveURL(BASE + '/')
    await expect(page.getByRole('heading', { name: 'Home' })).toBeVisible()
    await expect(page.locator('dialog')).toBeHidden()
    await expect(page).toHaveURL(BASE + '/')
    await page.goForward()
    await expect(page).toHaveURL(BASE + '/users/1')
    await expect(page.locator('dialog')).toBeVisible()
  })

  test('can navigate away from the modal then come back', async ({ page }) => {
    await page.goto(BASE + '/')
    await expect(page.getByRole('heading', { name: 'Home' })).toBeVisible()

    await userItem(page, 'Jessica')
      .getByRole('button', { name: 'Details' })
      .click()
    await expect(page.locator('dialog')).toBeVisible()
    await page
      .locator('dialog')
      .getByRole('link', { name: 'Go somewhere else' })
      .click()
    await expect(page).toHaveURL(BASE + '/about')
    await expect(page.getByRole('heading', { name: 'About' })).toBeVisible()
    await page.goBack()
    await expect(page).toHaveURL(BASE + '/users/1')
    await expect(page.locator('dialog')).toBeVisible()
    await page.goForward()
    await expect(page).toHaveURL(BASE + '/about')
    await expect(page.getByRole('heading', { name: 'About' })).toBeVisible()
    await page.goBack()
    await expect(page).toHaveURL(BASE + '/users/1')
    await expect(page.locator('dialog')).toBeVisible()
  })
})
