import { test, expect } from '@playwright/test'
import { reloadKeepingState } from './utils'

const baseURL = 'http://localhost:3000/modal'

test.describe('modal', () => {
  test('changes the url', async ({ page }) => {
    await page.goto(baseURL + '/')
    await expect(page.locator('#app > *').first()).toBeVisible()
    await expect(page.locator('h1')).toContainText('Home')
    await expect(page.locator('dialog')).toBeHidden()
    await expect(page.locator('.child')).toContainText('child')

    await page.locator('li:nth-child(2) button').click()
    await expect(page).toHaveURL(baseURL + '/users/1')
    await expect(page.locator('dialog')).toBeVisible()
    await expect(page.locator('dialog')).toContainText('User #1')
    await expect(page.locator('.child')).toContainText('child')
  })

  test('can close and reopen the modal through history', async ({ page }) => {
    await page.goto(baseURL + '/')
    await expect(page.locator('#app > *').first()).toBeVisible()
    await expect(page.locator('h1')).toContainText('Home')

    await page.locator('li:nth-child(2) button').click()
    await expect(page.locator('dialog')).toBeVisible()
    await page.goBack()
    await expect(page.locator('dialog')).toBeHidden()
    await expect(page).toHaveURL(baseURL + '/')
    await page.goForward()
    await expect(page.locator('dialog')).toBeVisible()
    await expect(page).toHaveURL(baseURL + '/users/1')
    await page.goBack()
    await expect(page.locator('dialog')).toBeHidden()
    await expect(page).toHaveURL(baseURL + '/')
    await page.goForward()
    await expect(page.locator('dialog')).toBeVisible()
    await expect(page).toHaveURL(baseURL + '/users/1')
  })

  test('can keep the modal when reloading', async ({ page }) => {
    await page.goto(baseURL + '/')
    await expect(page.locator('#app > *').first()).toBeVisible()
    await expect(page.locator('h1')).toContainText('Home')

    await page.locator('li:nth-child(2) button').click()
    await expect(page.locator('dialog')).toBeVisible()
    // the modal app restores its background view from history.state on reload
    await reloadKeepingState(page)
    await expect(page).toHaveURL(baseURL + '/users/1')
    await expect(page.locator('h1')).toContainText('Home')
    await expect(page.locator('dialog')).toBeVisible()
    await page.goBack()
    await expect(page).toHaveURL(baseURL + '/')
    await expect(page.locator('h1')).toContainText('Home')
    await expect(page.locator('dialog')).toBeHidden()
  })

  test('can pass through the modal and then back', async ({ page }) => {
    await page.goto(baseURL + '/')
    await expect(page.locator('#app > *').first()).toBeVisible()
    await expect(page.locator('h1')).toContainText('Home')
    await expect(page.locator('dialog')).toBeHidden()

    await page.locator('li:nth-child(2) a').click()
    await expect(page).toHaveURL(baseURL + '/users/1')
    await expect(page.locator('h1')).toContainText('User #1')
    await page.locator('#app a').click()
    await expect(page).toHaveURL(baseURL + '/')
    await expect(page.locator('h1')).toContainText('Home')
    await page.locator('li:nth-child(3) a').click()
    await expect(page).toHaveURL(baseURL + '/users/2')
    await expect(page.locator('h1')).toContainText('User #2')
    await page.locator('#app a').click()
    await expect(page).toHaveURL(baseURL + '/')
    await expect(page.locator('h1')).toContainText('Home')
    await page.locator('li:nth-child(2) button').click()
    await expect(page).toHaveURL(baseURL + '/users/1')
    await expect(page.locator('dialog')).toBeVisible()
    await page.goBack()
    await expect(page.locator('dialog')).toBeHidden()
    await expect(page).toHaveURL(baseURL + '/')
    await page.goBack()
    await expect(page).toHaveURL(baseURL + '/users/2')
    await expect(page.locator('h1')).toContainText('User #2')
    await page.goBack()
    await expect(page).toHaveURL(baseURL + '/')
    await expect(page.locator('h1')).toContainText('Home')
    await page.goBack()
    await expect(page).toHaveURL(baseURL + '/users/1')
    await expect(page.locator('h1')).toContainText('User #1')
    await page.goBack()
    await expect(page).toHaveURL(baseURL + '/')
    await expect(page.locator('h1')).toContainText('Home')
    await page.goForward()
    await expect(page).toHaveURL(baseURL + '/users/1')
    await expect(page.locator('h1')).toContainText('User #1')
    await page.goForward()
    await expect(page).toHaveURL(baseURL + '/')
    await expect(page.locator('h1')).toContainText('Home')
    await page.goForward()
    await expect(page).toHaveURL(baseURL + '/users/2')
    await expect(page.locator('h1')).toContainText('User #2')
    await page.goForward()
    await expect(page).toHaveURL(baseURL + '/')
    await expect(page.locator('h1')).toContainText('Home')
    await expect(page.locator('dialog')).toBeHidden()
    await expect(page).toHaveURL(baseURL + '/')
    await page.goForward()
    await expect(page).toHaveURL(baseURL + '/users/1')
    await expect(page.locator('dialog')).toBeVisible()
  })

  test('can navigate away from the modal then come back', async ({ page }) => {
    await page.goto(baseURL + '/')
    await expect(page.locator('#app > *').first()).toBeVisible()
    await expect(page.locator('h1')).toContainText('Home')

    await page.locator('li:nth-child(2) button').click()
    await expect(page.locator('dialog')).toBeVisible()
    await page.locator('dialog a').click()
    await expect(page).toHaveURL(baseURL + '/about')
    await expect(page.locator('h1')).toContainText('About')
    await page.goBack()
    await expect(page).toHaveURL(baseURL + '/users/1')
    await expect(page.locator('dialog')).toBeVisible()
    await page.goForward()
    await expect(page).toHaveURL(baseURL + '/about')
    await expect(page.locator('h1')).toContainText('About')
    await page.goBack()
    await expect(page).toHaveURL(baseURL + '/users/1')
    await expect(page.locator('dialog')).toBeVisible()
  })
})
