name: "\U0001F41E Bug report"
description: Report an issue with Vue Router
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: "If possible, provide a boiled down editable reproduction with the [Vue.js Playground](https://play.vuejs.org/#eNqlVGtv2jAU/SteNgmqFRvoNk1Ziuiqat20R9VN/bJMU0gMuE1sy3YoFeK/79rOi0L7ZUIQ5z7OPfeeizdBkTCOb3UQBqyQQhm0QamiiaFnUqItmitRoN6qpL2YNwFKlIaqxouJN7QhNrf2JVJinx/zBrkP36OYI4RLTfs+3b8XouSm33sJab2j4Dio0oFfZGghc8if2MBoOZpc0jwXttiLiMCrM0v3gIM2SvDF5LxUinLjOSOZmGUYkcqHNhv0yjnwvMzzK3Ci7dbBEI8T8WRVA147ll8Zv0NGnMYBiYPJJwFndCkKGpHW/2RGMgNLk3Zm3/byIlLXjKw2u1g3jN4jUsVV7og0g4F5+Vlic0DRb7QQ6uGSaQOP48rocbtKDxo1Gz1tg650LWptqJStZbcN7cQ1lmYF6NqFpoLrShSFTne49De2vaWnGR7i3j86tiEuW4fotx/RxquLeqQHzQmgxEH4sCW/dVndQKfHbnTbgw//A79bWE0Ybbdpu486VUwapKkpJcoTvgCJjQZ5rSbeCUd4ebS440mNBGs73lNwZ2b/V6eBOljIqzYoEgkXgOBQyk0+rhxQIUTOYm3tYlhzHCyNkTokpOTyboFhgKSNmL4lGSjVsWCqi8FMiXsN51tArqSIAy60YamrdQi0ck9HHpHxjK5xsYMwhTIkoysjRK4HiWRPYe0FTt/jER63XLu+Pca2HNwNWxic0bC+c7Z4NDa7RSyn6oc0DNZ7Z3wJ3FT3X5zNqJI25NMlTe8O2G/12rdxpSgwWNFOwyZRCwrXiHVf/PxO13BunIXIyhyin3FeUy3y0nL0YR9LngHtTpxj+9ltAeOLX/pibSjXdVOWqJuGi3ercf5M6y3dE/ymM0VtHnKqcartVQV33jGyF5rPmwmVURWisVwjIMsy9HI4HH6wrgLgGB/MhDGiCNFoKNfOLpMsA7KNBarEHGDRBCXoNXwdcJWd0zn817uRy3G3cgvfEkjTtEMgREP4jCsEaOev0TdU2SFBO+/wEJ8E2395AHxh), or an **editable** and **up to date** [CodeSandbox](https://codesandbox.io/s/vue-router-4-reproduction-s1sqc), Stackblitz, or a GitHub repository. A failing unit test is even better! Otherwise provide as much information as possible to reproduce the problem. If we can't reproduce the problem, we won't be able to give it a look **and the issue will be converted into a question and moved to discussions**."
      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the bug
      description: |
        1. Click on ...
        2. Check logs
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: 'A clear and concise description of what actually happens.'
    validations:
      required: true
  - type: textarea
    id: other-info
    attributes:
      label: Additional information
      description: Add any other context about the problem here.
  - type: markdown
    attributes:
      value: |
        ## Before creating an issue make sure that:
        - This hasn't been [reported before](https://github.com/vuejs/router/issues).
        - The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug **with no external dependencies (e.g. Vuetify or Nuxt)**
