/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/(home)': RouteRecordInfo<
      '/(home)',
      '/',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/hmr-alias': RouteRecordInfo<
      '/hmr-alias',
      '/hmr-alias',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/hmr-meta': RouteRecordInfo<
      '/hmr-meta',
      '/hmr-meta',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/hmr-name': RouteRecordInfo<
      '/hmr-name',
      '/hmr-name',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/hmr-params-[id]': RouteRecordInfo<
      '/hmr-params-[id]',
      '/hmr-params-:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/hmr-path': RouteRecordInfo<
      '/hmr-path',
      '/hmr-path',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/hmr-update': RouteRecordInfo<
      '/hmr-update',
      '/hmr-update',
      Record<never, never>,
      Record<never, never>,
      never
    >
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(home).vue': {
      routes: '/(home)'
      views: never
    }
    'src/pages/hmr-alias.vue': {
      routes: '/hmr-alias'
      views: never
    }
    'src/pages/hmr-meta.vue': {
      routes: '/hmr-meta'
      views: never
    }
    'src/pages/hmr-name.vue': {
      routes: '/hmr-name'
      views: never
    }
    'src/pages/hmr-params-[id].vue': {
      routes: '/hmr-params-[id]'
      views: never
    }
    'src/pages/hmr-path.vue': {
      routes: '/hmr-path'
      views: never
    }
    'src/pages/hmr-update.vue': {
      routes: '/hmr-update'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
