name: Publish Any Commit

on:
  pull_request:
    branches: main
    paths-ignore:
      - 'packages/docs/**'
      - 'packages/playground/**'

  push:
    branches:
      - '**'
    tags:
      - '!**'
    paths-ignore:
      - 'packages/docs/**'
      - 'packages/playground/**'

permissions:
  contents: read

jobs:
  build:
    if: github.repository == 'vuejs/router'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm -C packages/router build

      - name: Release
        run: pnpm dlx pkg-pr-new publish --compact --pnpm './packages/*' --packageManager=pnpm,npm,yarn
